### PR TITLE
Add ability to read JWT from query parameters.

### PR DESCRIPTION
**Pull request by graineri**
* Add default query parameter name (auth_token).
* Fixed body token field to be read according to options.
* Add tests.

### CODE REVIEW

**Comment by BDiehr** [comment]
+1

**Comment by themikenicholson** [comment]
Thanks for the great contribution.  I really appreciate the test coverage. Included in the latest release!

**Comment by nathanboktae** [comment]
Great! Could we get a new version published too please?

**Comment by themikenicholson** [comment]
1.1.0 should have been published before I made that comment.  I just verified npm install passport-jwt pulled down the latest version in an empty directory.  Are you not seeing the changes?

**Comment by nathanboktae** [comment]
I see it now - my browser just cached the page it seems. Thanks!

**Pull request merged**
