### PR TITLE
allow secretOrKey to be a function rather than a string or buffer

### PR DESCRIPTION
**Pull request by davesag**
thus enabling secret lookups in multi-tennanted applications.

Resolves issue #37

### CODE REVIEW

**Comment by mitermayer** [comment]
@themikenicholson Would be great if we can get this merged, we have a big project that at the moment is using a custom jwt middleware for express because of the lack of multi-tenancy support from passport-jwt.

**Comment by mitermayer** [comment]
@themikenicholson, sorry for sending another message, but could you please have a look into this PR it really would be great to get it merged ASAP

**Comment by thomas-hilaire** [comment]
Hello, I was needing almost the thing but for the whole `options` so I submitted a new pull-request, see #45.

@mitermayer until these pull-requests are merged, you are free to depend on "linagora/passport-jwt#v1.2.2-linagora" which contain my pull-request.

**Comment by swarajban** [comment]
Thanks @davesag. This is just what I needed

**Comment by swarajban** [comment]
If anyone also needs the original request object in the `secretOrKey`, I have created fork here: https://github.com/swarajban/passport-jwt

**Comment by manast** [comment]
@themikenicholson is there any blocker why this cant be merged? 
I am actually quite confused about how this module can be used in real life apps where you normally have more than one user accessing the system, are they supposed to share the same secret key ?

**Comment by manast** [comment]
@davesag The callback signature *secretOrKey( token, doneFn )* does not seem to be enough to be able to determine which user is actually accessing the API, how do you find the User's secret based just on a JWT token? I would expect that the callback can access the *request* object so that for example you can define a route like: ```router.get('/jwt/:id', passport.authenticate('jwt'), createSession);``` where ```req.params.id``` includes the userId for example, so we could do something like:
```javascript
secretOrKey function(req, doneFn) {
  User.findById(req.id, function(err, user){
   done(err, user ? user.secret );
  });
} 
```

**Comment by davesag** [comment]
@manst in my original use-case I believe we just decoded the user's details from the JWT but without validating it against the secret.  The issue we had was there were different secrets for different users and our app was multi-tenanted. It's all a bit academic now as that project ended late last year and was a purely internal project for a client.  I no longer have the source code.  That said, what you propose also makes sense.

**Comment by swarajban** [comment]
@manast in my PR above, I have added the request object to the secretOrKey function for this exact reason

**Comment by nainy** [comment]
Will this ever be accepted? Really looking forward to this.

**Comment by itotallyrock** [comment]
I hope so, I've had to resort to doing what several other people in this thread have done.  Modify our local versions to use it how we need.

**Comment by themikenicholson** [comment]
Duplicated by #108 which I'm currently working to get merged.  Closing this.

**Pull request closed without merging**
